import type { Project, TaskComment, TaskItem, User, UserPreference } from '@/types/models'

export interface MockDatabase {
  schemaVersion: 1
  users: User[]
  projects: Project[]
  tasks: TaskItem[]
  comments: TaskComment[]
  preferences: UserPreference[]
}

const now = '2026-08-23T08:00:00.000Z'

export const seedDatabase = (): MockDatabase => ({
  schemaVersion: 1,
  users: [
    {
      id: 'u-admin',
      account: 'admin',
      displayName: 'Ada Admin',
      email: 'admin@demo.local',
      role: 'Admin',
      isVerified: true,
      isEnabled: true,
      createdAt: now,
    },
    {
      id: 'u-administrator',
      account: 'administrator',
      displayName: 'Alex Manager',
      email: 'administrator@demo.local',
      role: 'Administrator',
      isVerified: true,
      isEnabled: true,
      createdAt: now,
    },
    {
      id: 'u-user',
      account: 'user',
      displayName: 'Lisa Chen',
      email: 'user@demo.local',
      role: 'User',
      isVerified: true,
      isEnabled: true,
      createdAt: now,
    },
    {
      id: 'u-viewer',
      account: 'viewer',
      displayName: 'Victor Lin',
      email: 'viewer@demo.local',
      role: 'Viewer',
      isVerified: true,
      isEnabled: true,
      createdAt: now,
    },
    {
      id: 'u-pending',
      account: 'pending',
      displayName: 'Penny Wu',
      email: 'pending@demo.local',
      role: 'Viewer',
      isVerified: false,
      isEnabled: true,
      createdAt: now,
    },
  ],
  projects: [
    {
      id: 'PRJ-1001',
      name: 'Customer Portal',
      description: '打造客戶自助服務與案件追蹤入口。',
      ownerId: 'u-administrator',
      status: 'Active',
      createdAt: '2026-07-01T08:00:00.000Z',
      updatedAt: now,
      version: 1,
      members: [
        { userId: 'u-administrator', projectRole: 'ProjectManager' },
        { userId: 'u-user', projectRole: 'FrontendDeveloper' },
        { userId: 'u-viewer', projectRole: 'Member' },
      ],
    },
    {
      id: 'PRJ-1002',
      name: 'Internal Operations',
      description: '整合內部表單與跨部門工作流程。',
      ownerId: 'u-admin',
      status: 'Active',
      createdAt: '2026-07-15T08:00:00.000Z',
      updatedAt: now,
      version: 1,
      members: [
        { userId: 'u-admin', projectRole: 'ProjectManager' },
        { userId: 'u-administrator', projectRole: 'SystemAnalyst' },
        { userId: 'u-user', projectRole: 'FrontendDeveloper' },
      ],
    },
    {
      id: 'PRJ-1003',
      name: 'Legacy Migration',
      description: '歷史系統資料與功能遷移。',
      ownerId: 'u-admin',
      status: 'Archived',
      createdAt: '2026-05-01T08:00:00.000Z',
      updatedAt: now,
      version: 1,
      members: [{ userId: 'u-admin', projectRole: 'ProjectManager' }],
    },
  ],
  tasks: [
    {
      id: 'TASK-101',
      projectId: 'PRJ-1001',
      title: '建立登入頁面',
      description: '完成登入、錯誤回饋與 RWD。',
      creatorId: 'u-administrator',
      assigneeId: 'u-user',
      startAt: '2026-08-20T01:00:00.000Z',
      deadline: '2026-08-28T09:00:00.000Z',
      status: 'InProgress',
      createdAt: '2026-08-18T01:00:00.000Z',
      updatedAt: now,
      version: 1,
      deletedAt: null,
    },
    {
      id: 'TASK-102',
      projectId: 'PRJ-1001',
      title: '確認 API contract',
      description: '整理登入與使用者 API 欄位。',
      creatorId: 'u-administrator',
      assigneeId: 'u-administrator',
      startAt: '2026-08-18T01:00:00.000Z',
      deadline: '2026-08-25T09:00:00.000Z',
      status: 'Blocked',
      createdAt: '2026-08-17T01:00:00.000Z',
      updatedAt: now,
      version: 1,
      deletedAt: null,
    },
    {
      id: 'TASK-103',
      projectId: 'PRJ-1001',
      title: '設定設計 Tokens',
      description: '定義顏色、間距與字體。',
      creatorId: 'u-administrator',
      assigneeId: 'u-user',
      startAt: '2026-08-16T01:00:00.000Z',
      deadline: '2026-08-22T09:00:00.000Z',
      status: 'Completed',
      createdAt: '2026-08-16T01:00:00.000Z',
      updatedAt: now,
      version: 1,
      deletedAt: null,
    },
    {
      id: 'TASK-201',
      projectId: 'PRJ-1002',
      title: '盤點作業流程',
      description: '訪談各部門並整理現況。',
      creatorId: 'u-admin',
      assigneeId: 'u-administrator',
      startAt: '2026-08-21T01:00:00.000Z',
      deadline: '2026-09-02T09:00:00.000Z',
      status: 'Pending',
      createdAt: '2026-08-21T01:00:00.000Z',
      updatedAt: now,
      version: 1,
      deletedAt: null,
    },
  ],
  comments: [
    {
      id: 'comment-1',
      taskId: 'TASK-101',
      authorId: 'u-administrator',
      content: '請先完成桌面版，再確認手機版斷點。',
      createdAt: '2026-08-20T02:00:00.000Z',
      updatedAt: '2026-08-20T02:00:00.000Z',
      deletedAt: null,
    },
    {
      id: 'comment-2',
      taskId: 'TASK-101',
      authorId: 'u-user',
      content: '桌面版已完成，正在調整 Sidebar。',
      createdAt: '2026-08-22T02:00:00.000Z',
      updatedAt: '2026-08-22T02:00:00.000Z',
      deletedAt: null,
    },
  ],
  preferences: [],
})
